main: me.capit.Townshend.TownshendPlugin
version: 1.00R1
name: Townshend

author: Wehttam664
softdepend: [TagAPI]

commands:
  townshend:
    description: Basic Townshend command.
    usage: '/townshend help'
    aliases: ['town','t']
  group:
    description: Basic Group command.
    usage: '/group help'
    aliases: ['g']
    
permissions:
  townshend.*:
    description: Global Townshend permission.
    children:
      - townshend.player
      - townshend.admin
  townshend.player.*:
    description: Townshend player permissions.
    children:
      - townshend.player.create
      - townshend.player.modify
      - townshend.player.info
      - townshend.player.join
      - townshend.player.relations
  townshend.group.*:
    description: Townshend group permissions.
    children:
      - townshend.group.create
      - townshend.group.delete
      - townshend.group.add
      - townshend.group.remove
