main: me.capit.Townshend.TownshendPlugin
version: 1.00R1
name: Townshend

author: Wehttam664
softdepend: [TagAPI]

commands:
  townshend:
    description: Basic Townshend command.
    usage: '/townshend help'
    aliases: ['town','t']
